use_frameworks!
target 'Kitchen recipes'
pod 'Cosmos', '~> 15.0'
pod 'SwiftGifOrigin', '~> 1.6.1'
pod 'Gifu'
pod 'SwiftyGif'
pod 'YALSideMenu', '~> 2.0'
pod 'NVActivityIndicatorView'
pod 'Regift'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'SCLAlertView'
pod 'ObjectMapper', '~> 3.1'
